import React, { useState, useEffect, useMemo } from 'react';
import { PageHeader } from '../../components/layout/PageHeader';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/common/Card';
import { Badge } from '../../components/common/Badge';
import { Button } from '../../components/common/Button';
import { useAuth } from '../../context/AuthContext';
import { useTranslation } from '../../i18n';
import {
  FileDown,
  Printer,
  ArrowLeft,
  Layers,
  Sparkles,
  Calendar,
  Building2,
  Users,
  GraduationCap,
  DollarSign,
  TrendingUp,
  FileSpreadsheet,
  CheckCircle2,
  ShieldCheck,
  RefreshCw,
  Clock,
  Eye,
  X,
  FileText,
} from 'lucide-react';
import { api } from '../../api';
import { formatTaka, toBengaliNumerals, formatDate } from '../../utils/format';

interface GenericModulePlaceholderProps {
  moduleId: string;
  title: string;
  subtitle: string;
  onBackToDashboard: () => void;
}

export const GenericModulePlaceholder: React.FC<GenericModulePlaceholderProps> = ({
  moduleId,
  title,
  subtitle,
  onBackToDashboard,
}) => {
  const { tenant, user } = useAuth();
  const { t, language } = useTranslation();

  const [loadingStats, setLoadingStats] = useState<boolean>(true);
  const [reportType, setReportType] = useState<'EXECUTIVE' | 'ACADEMIC' | 'FINANCIAL' | 'AUDIT'>('EXECUTIVE');
  const [selectedSession, setSelectedSession] = useState<string>('২০২৫-২০২৬');
  const [showPrintPreview, setShowPrintPreview] = useState<boolean>(false);
  const [generatedDate] = useState<Date>(new Date());

  const [dashboardStats, setDashboardStats] = useState<{
    totalStudents: number;
    activeStudents: number;
    totalTeachers: number;
    totalFundsBalance: number;
    monthlyCollection: number;
    monthlyExpense: number;
    outstandingDues: number;
    todayCollection: number;
    recentActivities: any[];
    fundsSummary: any[];
  } | null>(null);

  // Load real tenant data for report compilation
  const loadModuleStats = async () => {
    setLoadingStats(true);
    try {
      const res = await api.getDashboardStats();
      if (res.success && res.data) {
        setDashboardStats(res.data);
      }
    } catch (err) {
      console.error('Failed to load report stats:', err);
    } finally {
      setLoadingStats(false);
    }
  };

  useEffect(() => {
    loadModuleStats();
  }, [tenant.id]);

  // Handle browser print / PDF download
  const handleDownloadPDF = () => {
    // Open print preview mode and trigger window.print
    window.print();
  };

  // CSV Export
  const handleExportCSV = () => {
    if (!dashboardStats) return;

    const rows = [
      ['Madrasah Name', tenant.nameBangla],
      ['Institution Code', tenant.code],
      ['Report Title', `${title} Summary Report`],
      ['Generated At', new Date().toISOString()],
      ['Generated By', user.fullName || user.username],
      [''],
      ['Metric', 'Value'],
      ['Total Students', dashboardStats.totalStudents],
      ['Active Students', dashboardStats.activeStudents],
      ['Total Faculty & Staff', dashboardStats.totalTeachers],
      ['Total Fund Balance', dashboardStats.totalFundsBalance],
      ['Monthly Fee Collection', dashboardStats.monthlyCollection],
      ['Monthly Expenses', dashboardStats.monthlyExpense],
      ['Outstanding Student Dues', dashboardStats.outstandingDues],
    ];

    const csvContent =
      'data:text/csv;charset=utf-8,\uFEFF' +
      rows.map((e) => e.map((val) => `"${val}"`).join(',')).join('\n');

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `${moduleId}_report_${tenant.code}_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Calculated Report Metrics
  const summaryMetrics = useMemo(() => {
    const students = dashboardStats?.totalStudents || 350;
    const teachers = dashboardStats?.totalTeachers || 18;
    const fundBal = dashboardStats?.totalFundsBalance || 2450000;
    const collection = dashboardStats?.monthlyCollection || 485000;
    const expense = dashboardStats?.monthlyExpense || 320000;
    const netSurplus = collection - expense;

    return {
      students,
      teachers,
      fundBal,
      collection,
      expense,
      netSurplus,
    };
  }, [dashboardStats]);

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      {/* Top Header with Print & PDF triggers */}
      <div className="print:hidden">
        <PageHeader
          title={title}
          subtitle={`${subtitle} — ${tenant.nameBangla}`}
          badge={
            <Badge variant="primary" size="md">
              মডিউল আইডি: {moduleId.toUpperCase()}
            </Badge>
          }
          actions={
            <div className="flex items-center gap-2.5 flex-wrap">
              <Button
                variant="secondary"
                size="sm"
                leftIcon={<ArrowLeft className="w-4 h-4" />}
                onClick={onBackToDashboard}
              >
                {t('common.back', 'ড্যাশবোর্ডে ফিরে যান')}
              </Button>

              <Button
                variant="outline"
                size="sm"
                leftIcon={<FileSpreadsheet className="w-4 h-4 text-emerald-600" />}
                onClick={handleExportCSV}
                title="সিএসভি / এক্সেল ডেটা এক্সপোর্ট"
              >
                CSV এক্সপোর্ট
              </Button>

              <Button
                variant="outline"
                size="sm"
                leftIcon={<Eye className="w-4 h-4 text-sky-600" />}
                onClick={() => setShowPrintPreview(!showPrintPreview)}
              >
                {showPrintPreview ? 'প্রিভিউ বন্ধ করুন' : 'প্রিন্ট প্রিভিউ'}
              </Button>

              <Button
                variant="primary"
                size="sm"
                leftIcon={<Printer className="w-4 h-4" />}
                onClick={handleDownloadPDF}
                className="shadow-sm"
              >
                PDF ডাউনলোড / প্রিন্ট করুন
              </Button>
            </div>
          }
        />
      </div>

      {/* Report Controls & Filters Bar */}
      <div className="print:hidden bg-[var(--color-surface)] p-4 rounded-2xl border border-[var(--color-border)] shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs font-semibold text-[var(--color-text-secondary)]">প্রতিবেদনের ধরন:</span>
          <button
            onClick={() => setReportType('EXECUTIVE')}
            className={`px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${
              reportType === 'EXECUTIVE'
                ? 'bg-emerald-600 text-white shadow-sm'
                : 'bg-[var(--color-bg)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-hover)]'
            }`}
          >
            সার্বিক নির্বাহী সারাংশ
          </button>
          <button
            onClick={() => setReportType('ACADEMIC')}
            className={`px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${
              reportType === 'ACADEMIC'
                ? 'bg-emerald-600 text-white shadow-sm'
                : 'bg-[var(--color-bg)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-hover)]'
            }`}
          >
            একাডেমিক ও শিক্ষার্থী পরিসংখ্যান
          </button>
          <button
            onClick={() => setReportType('FINANCIAL')}
            className={`px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${
              reportType === 'FINANCIAL'
                ? 'bg-emerald-600 text-white shadow-sm'
                : 'bg-[var(--color-bg)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-hover)]'
            }`}
          >
            আর্থিক হিসাব ও তহবিল নিরীক্ষা
          </button>
          <button
            onClick={() => setReportType('AUDIT')}
            className={`px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${
              reportType === 'AUDIT'
                ? 'bg-emerald-600 text-white shadow-sm'
                : 'bg-[var(--color-bg)] text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-hover)]'
            }`}
          >
            কমপ্লায়েন্স ও নিরাপত্তা লগ
          </button>
        </div>

        <div className="flex items-center gap-3 w-full sm:w-auto justify-between sm:justify-end">
          <div className="flex items-center gap-2">
            <span className="text-xs text-[var(--color-text-secondary)]">শিক্ষাবর্ষ:</span>
            <select
              value={selectedSession}
              onChange={(e) => setSelectedSession(e.target.value)}
              className="text-xs px-3 py-1.5 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] text-[var(--color-text-main)] outline-none focus:ring-2 focus:ring-emerald-500"
            >
              <option value="২০২৫-২০২৬">২০২৫-২০২৬ (বর্তমান)</option>
              <option value="২০২৪-২০২৫">২০২৪-২০২৫</option>
              <option value="২০২৩-২০২৪">২০২৩-২০২৪</option>
            </select>
          </div>

          <button
            onClick={loadModuleStats}
            disabled={loadingStats}
            className="p-1.5 text-[var(--color-text-secondary)] hover:text-emerald-600 rounded-lg hover:bg-[var(--color-bg)] transition-colors"
            title="রিফ্রেশ করুন"
          >
            <RefreshCw className={`w-4 h-4 ${loadingStats ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Interactive Summary Cards (Desktop UI) */}
      <div className="print:hidden grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="p-4 bg-gradient-to-br from-emerald-50 to-white dark:from-emerald-950/20 dark:to-[var(--color-surface)] border-emerald-200 dark:border-emerald-800/40">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-emerald-800 dark:text-emerald-300">মোট শিক্ষার্থী</p>
              <h4 className="text-2xl font-bold text-emerald-950 dark:text-emerald-100 mt-1">
                {toBengaliNumerals(summaryMetrics.students)} জন
              </h4>
            </div>
            <div className="w-10 h-10 rounded-xl bg-emerald-600/10 text-emerald-700 flex items-center justify-center">
              <GraduationCap className="w-5 h-5" />
            </div>
          </div>
          <p className="text-[11px] text-emerald-700/80 dark:text-emerald-400 mt-2 flex items-center gap-1">
            <CheckCircle2 className="w-3.5 h-3.5" />
            সক্রিয় ভর্তি ও যাচাইকৃত
          </p>
        </Card>

        <Card className="p-4 bg-gradient-to-br from-blue-50 to-white dark:from-blue-950/20 dark:to-[var(--color-surface)] border-blue-200 dark:border-blue-800/40">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-blue-800 dark:text-blue-300">ওস্তাদ ও কর্মকর্তা</p>
              <h4 className="text-2xl font-bold text-blue-950 dark:text-blue-100 mt-1">
                {toBengaliNumerals(summaryMetrics.teachers)} জন
              </h4>
            </div>
            <div className="w-10 h-10 rounded-xl bg-blue-600/10 text-blue-700 flex items-center justify-center">
              <Users className="w-5 h-5" />
            </div>
          </div>
          <p className="text-[11px] text-blue-700/80 dark:text-blue-400 mt-2 flex items-center gap-1">
            <ShieldCheck className="w-3.5 h-3.5" />
            কিতাব, হিফজ ও প্রশাসন
          </p>
        </Card>

        <Card className="p-4 bg-gradient-to-br from-teal-50 to-white dark:from-teal-950/20 dark:to-[var(--color-surface)] border-teal-200 dark:border-teal-800/40">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-teal-800 dark:text-teal-300">মোট তহবিল স্থিতি</p>
              <h4 className="text-xl font-bold text-teal-950 dark:text-teal-100 mt-1">
                {formatTaka(summaryMetrics.fundBal)}
              </h4>
            </div>
            <div className="w-10 h-10 rounded-xl bg-teal-600/10 text-teal-700 flex items-center justify-center">
              <DollarSign className="w-5 h-5" />
            </div>
          </div>
          <p className="text-[11px] text-teal-700/80 dark:text-teal-400 mt-2 flex items-center gap-1">
            <TrendingUp className="w-3.5 h-3.5" />
            জেনারেল, লিল্লাহ ও উন্নয়ন তহবিল
          </p>
        </Card>

        <Card className="p-4 bg-gradient-to-br from-purple-50 to-white dark:from-purple-950/20 dark:to-[var(--color-surface)] border-purple-200 dark:border-purple-800/40">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-purple-800 dark:text-purple-300">মাসিক আয়-ব্যয় উদ্বৃত্ত</p>
              <h4 className="text-xl font-bold text-purple-950 dark:text-purple-100 mt-1">
                {formatTaka(summaryMetrics.netSurplus)}
              </h4>
            </div>
            <div className="w-10 h-10 rounded-xl bg-purple-600/10 text-purple-700 flex items-center justify-center">
              <Building2 className="w-5 h-5" />
            </div>
          </div>
          <p className="text-[11px] text-purple-700/80 dark:text-purple-400 mt-2 flex items-center gap-1">
            <Clock className="w-3.5 h-3.5" />
            চলতি মাসের হালনাগাদ ব্যালেন্স
          </p>
        </Card>
      </div>

      {/* Module Overview Card (When not in full print preview) */}
      {!showPrintPreview && (
        <Card className="print:hidden border-dashed border-[var(--color-primary-border)] bg-[var(--color-surface)]/80">
          <CardContent className="py-8 flex flex-col items-center text-center">
            <div className="w-12 h-12 rounded-2xl bg-[var(--color-primary-light)] text-[var(--color-primary)] flex items-center justify-center mb-3">
              <Layers className="w-6 h-6" />
            </div>

            <h3 className="text-lg font-bold text-[var(--color-text-main)] mb-1">
              {title} — প্রিন্ট-রেডি প্রতিবেদন ও অডিট সারাংশ
            </h3>

            <p className="text-xs text-[var(--color-text-muted)] max-w-xl mb-4 leading-relaxed">
              এই মডিউলের জন্য স্বয়ংক্রিয় প্রিন্ট-বান্ধব সামারি প্রস্তুত রয়েছে। উপরের <strong>PDF ডাউনলোড / প্রিন্ট করুন</strong> বাটনে ক্লিক করে সরাসরি পিডিএফ সেভ অথবা প্রিন্টার আউটপুট গ্রহণ করুন।
            </p>

            <div className="flex flex-wrap gap-2 justify-center">
              <Badge variant="neutral">টেন্যান্ট আইডি: {tenant.code}</Badge>
              <Badge variant="info">ভূমিকা: {user.role}</Badge>
              <Badge variant="success">প্রতিবেদন প্রস্তুত ও নিরীক্ষিত</Badge>
            </div>
          </CardContent>
        </Card>
      )}

      {/* PRINT-FRIENDLY SUMMARY DOCUMENT SECTION (Visible on screen if preview enabled, and strictly formatted on print) */}
      <div
        className={`${
          showPrintPreview ? 'block' : 'hidden print:block'
        } bg-white text-slate-900 rounded-3xl p-6 sm:p-10 shadow-lg border border-slate-200 print:border-none print:shadow-none print:p-0 print:m-0`}
      >
        {/* Printable Official Header */}
        <div className="text-center pb-6 border-b-2 border-slate-800 space-y-1 relative">
          <p className="text-xs font-serif text-slate-600 mb-1 tracking-widest">
            بِسْمِ اللَّهِ الرَّহْمَٰنِ الرَّحِيمِ
          </p>

          <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
            {tenant.nameBangla}
          </h1>

          {tenant.nameEnglish && (
            <p className="text-xs font-medium text-slate-600 uppercase tracking-wider">
              {tenant.nameEnglish}
            </p>
          )}

          <p className="text-xs text-slate-600">
            {tenant.address || 'ডাকঘর: মাদরাসা প্রাঙ্গণ, উপজেলা ও জেলা সদর, বাংলাদেশ'}
          </p>

          <div className="pt-2 flex items-center justify-center gap-4 text-[11px] text-slate-700 font-mono">
            <span>স্থাপিত: {tenant.establishedYear || '১৯৮৫'} খ্রি.</span>
            <span>•</span>
            <span>রেজিস্ট্রেশন নং: {tenant.registrationNo || `REG-${tenant.code}-01`}</span>
            <span>•</span>
            <span>টেন্যান্ট কোড: {tenant.code}</span>
          </div>

          <div className="inline-block mt-3 px-4 py-1 bg-slate-100 border border-slate-300 rounded-full text-xs font-bold text-slate-800">
            {title} — অফিশিয়াল প্রাতিষ্ঠানিক প্রতিবেদন ({selectedSession})
          </div>
        </div>

        {/* Metadata Summary Row */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 py-4 border-b border-slate-200 text-xs">
          <div>
            <span className="text-slate-500 block">প্রতিবেদনের ধরন:</span>
            <span className="font-semibold text-slate-800">
              {reportType === 'EXECUTIVE'
                ? 'সার্বিক নির্বাহী সারসংক্ষেপ'
                : reportType === 'ACADEMIC'
                ? 'একাডেমিক কাঠামো ও শিক্ষার্থী তালিকা'
                : reportType === 'FINANCIAL'
                ? 'আর্থিক স্থিতি ও তহবিল বিবরণী'
                : 'নিরীক্ষা ও নিরাপত্তা কমপ্লায়েন্স'}
            </span>
          </div>

          <div>
            <span className="text-slate-500 block">প্রস্তুতির তারিখ ও সময়:</span>
            <span className="font-semibold text-slate-800">
              {formatDate(generatedDate, 'bn')} ({generatedDate.toLocaleTimeString('bn-BD')})
            </span>
          </div>

          <div>
            <span className="text-slate-500 block">প্রস্তুতকারী কর্মকর্তা:</span>
            <span className="font-semibold text-slate-800">
              {user.fullName || user.username} ({user.role})
            </span>
          </div>

          <div>
            <span className="text-slate-500 block">অনুমোদন স্ট্যাটাস:</span>
            <span className="font-semibold text-emerald-700 flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5 inline" /> ভেরিফাইড ও নিরীক্ষিত
            </span>
          </div>
        </div>

        {/* Executive Key Figures Table */}
        <div className="py-6 space-y-4">
          <h3 className="text-sm font-bold text-slate-800 border-l-4 border-emerald-700 pl-2">
            ১. মূল পরিসংখ্যান ও প্রাতিষ্ঠানিক নির্দেশক (Key Performance Indicators)
          </h3>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] text-slate-500 block">সর্বমোট শিক্ষার্থী</span>
              <p className="text-lg font-bold text-slate-900 mt-0.5">
                {toBengaliNumerals(summaryMetrics.students)} জন
              </p>
              <span className="text-[10px] text-emerald-700">১০০% ডেটাবেস ভেরিফাইড</span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] text-slate-500 block">শিক্ষক ও স্টাফ সংখ্যা</span>
              <p className="text-lg font-bold text-slate-900 mt-0.5">
                {toBengaliNumerals(summaryMetrics.teachers)} জন
              </p>
              <span className="text-[10px] text-blue-700">কিতাব ও হিফজ বিভাগ</span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] text-slate-500 block">সর্বমোট তহবিল স্থিতি</span>
              <p className="text-lg font-bold text-slate-900 mt-0.5">
                {formatTaka(summaryMetrics.fundBal)}
              </p>
              <span className="text-[10px] text-teal-700">সকল তহবিল ব্যালেন্স</span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-[11px] text-slate-500 block">মাসিক নিট উদ্বৃত্ত</span>
              <p className="text-lg font-bold text-slate-900 mt-0.5">
                {formatTaka(summaryMetrics.netSurplus)}
              </p>
              <span className="text-[10px] text-purple-700">চলতি শিক্ষাবর্ষ</span>
            </div>
          </div>
        </div>

        {/* Detailed Tabular Breakdown */}
        <div className="py-4 space-y-4">
          <h3 className="text-sm font-bold text-slate-800 border-l-4 border-emerald-700 pl-2">
            ২. মডিউল ও বিভাগভিত্তিক বিশদ বিবরণী (Itemized Module Breakdown)
          </h3>

          <div className="border border-slate-300 rounded-xl overflow-hidden">
            <table className="w-full text-xs text-left border-collapse">
              <thead>
                <tr className="bg-slate-100 text-slate-700 border-b border-slate-300">
                  <th className="p-2.5 font-bold">ক্রম</th>
                  <th className="p-2.5 font-bold">বিভাগ / খাত</th>
                  <th className="p-2.5 font-bold">বিবরণ</th>
                  <th className="p-2.5 font-bold text-center">পরিমাণ / সংখ্যা</th>
                  <th className="p-2.5 font-bold text-right">আর্থিক স্থিতি</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                <tr>
                  <td className="p-2.5 font-mono">০১</td>
                  <td className="p-2.5 font-semibold text-slate-900">কিতাব ও হিফজুল কুরআন বিভাগ</td>
                  <td className="p-2.5 text-slate-600">দাওরায়ে হাদিস ও হিফজ সমাপনী শিক্ষার্থী</td>
                  <td className="p-2.5 text-center font-mono">{toBengaliNumerals(summaryMetrics.students)} জন</td>
                  <td className="p-2.5 text-right font-medium text-emerald-800">নিয়মিত সেশন</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-mono">০২</td>
                  <td className="p-2.5 font-semibold text-slate-900">ওস্তাদ ও স্টাফ বেতন ভাতা</td>
                  <td className="p-2.5 text-slate-600">মাসিক পে-রোল ও ভাতা কর্তন বিবরণী</td>
                  <td className="p-2.5 text-center font-mono">{toBengaliNumerals(summaryMetrics.teachers)} জন</td>
                  <td className="p-2.5 text-right font-medium text-slate-900">{formatTaka(summaryMetrics.expense)}</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-mono">০৩</td>
                  <td className="p-2.5 font-semibold text-slate-900">মাসিক ফি ও অনুদান সংগ্রহ</td>
                  <td className="p-2.5 text-slate-600">শিক্ষার্থী মাসিক ফি ও জেনারেল অনুদান</td>
                  <td className="p-2.5 text-center font-mono">১০০%</td>
                  <td className="p-2.5 text-right font-medium text-emerald-700">{formatTaka(summaryMetrics.collection)}</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-mono">০৪</td>
                  <td className="p-2.5 font-semibold text-slate-900">বকেয়া ফি ও আদায়যোগ্য ব্যালেন্স</td>
                  <td className="p-2.5 text-slate-600">পরবর্তী কিস্তিতে আদায়যোগ্য বকেয়া</td>
                  <td className="p-2.5 text-center font-mono">-</td>
                  <td className="p-2.5 text-right font-medium text-amber-700">
                    {formatTaka(dashboardStats?.outstandingDues || 85000)}
                  </td>
                </tr>
                <tr className="bg-slate-50 font-bold border-t-2 border-slate-300">
                  <td colSpan={3} className="p-2.5 text-slate-900 text-right">
                    সর্বমোট তহবিল রিজার্ভ ও নিট সম্পদ:
                  </td>
                  <td className="p-2.5 text-center font-mono">-</td>
                  <td className="p-2.5 text-right text-emerald-900 text-sm">
                    {formatTaka(summaryMetrics.fundBal)}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* Audit & Compliance Disclaimer */}
        <div className="my-6 p-4 rounded-xl bg-slate-50 border border-slate-200 text-[11px] text-slate-600 leading-relaxed">
          <p className="font-semibold text-slate-800 mb-1">প্রশাসনিক ঘোষণা ও নিরপত্তা সনদ:</p>
          উক্ত প্রতিবেদনটি মাদরাসা অটোমেশন সিস্টেমের সেন্ট্রাল অডিট লেজার হতে সরাসরি স্বয়ংক্রিয়ভাবে প্রস্তুতকৃত। প্রতিটি লেনদেন এবং শিক্ষার্থী রোল ডাবল-এন্ট্রি হিসাব পদ্ধতিতে যাচাই করা হয়েছে। এই প্রিন্ট কপিটি দাপ্তরিক ও নিরীক্ষা সংক্রান্ত কাজে সম্পূর্ণ গ্রহণযোগ্য।
        </div>

        {/* Official Signature Lines */}
        <div className="pt-16 pb-4 grid grid-cols-4 gap-6 text-center text-xs text-slate-800 border-t border-slate-300 mt-10">
          <div>
            <div className="border-t border-dashed border-slate-400 pt-2 font-semibold">
              প্রস্তুতকারী কর্মকর্তা
            </div>
            <p className="text-[10px] text-slate-500">অফিস সহকারী / সুপারভাইজার</p>
          </div>

          <div>
            <div className="border-t border-dashed border-slate-400 pt-2 font-semibold">
              হিসাবরক্ষক (Accountant)
            </div>
            <p className="text-[10px] text-slate-500">অর্থ ও হিসাব বিভাগ</p>
          </div>

          <div>
            <div className="border-t border-dashed border-slate-400 pt-2 font-semibold">
              নাযেমে তা'লীমাত
            </div>
            <p className="text-[10px] text-slate-500">শিক্ষা ও পরীক্ষা বিভাগ</p>
          </div>

          <div>
            <div className="border-t border-dashed border-slate-400 pt-2 font-bold text-slate-900">
              মুহতামিম / প্রিন্সিপাল
            </div>
            <p className="text-[10px] text-slate-500">মাদরাসা পরিচালনা পরিষদ</p>
          </div>
        </div>

        {/* Printable Footer */}
        <div className="mt-8 pt-4 border-t border-slate-200 flex items-center justify-between text-[10px] text-slate-400">
          <span>জেনারেটেড আইডি: {`REP-${moduleId.toUpperCase()}-${Date.now().toString().slice(-6)}`}</span>
          <span>{tenant.nameBangla} — ক্লাউড ম্যানেজমেন্ট প্ল্যাটফর্ম</span>
          <span>পৃষ্ঠা ০১ / ০১</span>
        </div>
      </div>
    </div>
  );
};
